version: '3.7'

services:

  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: masp
      MYSQL_TLS_VERSION: TLSv1.2,TLSv1.3 
    volumes:
      - ./mysql:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 30s
      timeout: 10s
      retries: 10
 

  facial-recognition:
    hostname: facial-recognition
    build: ./FacialRecognition
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    image: facial-recognition:latest
    volumes:
      - ./FacialRecognition/:/app/
      - ./vector_index:/app/faiss/
    ports:
      - 8000:8000
    deploy:
      mode: replicated
      replicas: 1
    restart: always

